export enum FamilyStatus {
    WAITINGFORCHECK = 'WAITINGFORCHECK' ,
    WAITINGFORORDER = 'WAITINGFORORDER' ,
    DELIVERY = 'DELIVERY' ,
    NONEED = 'NONEED' ,
    STOPDELIVERING = 'STOPDELIVERING'
}
